[Updated] - Added rating to notes
YoussefMIbrahim/lmn pull request #30
Opened 2020-12-07 18:34 UTC by BrettKoenig04

2020-12-08 19:36 UTC, xd3262nd commented on lmn/templates/lmn/notes/note_detail.html
> +{% if note.rating == 1 %}
Should also have the star presented even there is no rating being given yet or write some statement saying no rating

2020-12-08 19:37 UTC, xd3262nd commented on lmn/templates/lmn/notes/note_list.html
> +
Same over here as well

2020-12-08 19:38 UTC, xd3262nd requested changes
Should probably add the user_images directory in your gitignore as well

2020-12-11 01:27 UTC, xd3262nd commented
@BrettKoenig04 Not sure if it is a bug but when a user add new note on the app and did not put any rating (or put rating 0) it will not save the note and did not print out any useful message for the user to know they have to put rating on the note.

2020-12-11 03:35 UTC, BrettKoenig04 commented
> Should probably add the user_images directory in your gitignore as well

Forgot about that, removed items from sub directory. Will do.

2020-12-11 18:46 UTC, xd3262nd commented on lmn/templates/lmn/notes/new_note.html
> +          {{ form.rating.errors }}
Works now! Is there a way to highlight this or move this on top of the form so is easily visible?

2020-12-12 20:01 UTC, xd3262nd approved these changes

2020-12-13 00:13 UTC, merged